sonar.projectKey=armaniaictt_github-actions-2025
sonar.organization=jomacs-github-actions-225


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=github-actions-2025
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
